// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8BuwN5Icn5LLU7RYbXCniu1TyN5QLQM',
    appId: '1:753564717002:android:e3f77aab23114140e0c933',
    messagingSenderId: '753564717002',
    projectId: 'myrefindapp',
    storageBucket: 'myrefindapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGVBbsigjPuLb0vFnjBm_SMgP6RR_aig',
    appId: '1:753564717002:ios:1bf19e28929ed512e0c933',
    messagingSenderId: '753564717002',
    projectId: 'myrefindapp',
    storageBucket: 'myrefindapp.firebasestorage.app',
    androidClientId: '753564717002-dqmnqp34j8ovs6d1eht4d837slf3tgri.apps.googleusercontent.com',
    iosClientId: '753564717002-6mb8frqnu5dla1idhqq4rc8r2memecb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.refindApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmdxaBYSLEu0esRbQepToLsKAhdk6KoM',
    appId: '1:753564717002:web:aaa6a97d0abb43e2e0c933',
    messagingSenderId: '753564717002',
    projectId: 'myrefindapp',
    authDomain: 'myrefindapp.firebaseapp.com',
    storageBucket: 'myrefindapp.firebasestorage.app',
    measurementId: 'G-PQBLK8YDDF',
  );

}